### ISSUE TITLE
Too restrictive on httparty

### ISSUE THREAD

**Issue by ivopashov** [quaderno/quaderno-ruby#13]
Hi,

is there a special reason why you are so restrictive on httparty gem (`spec.add_dependency('httparty', "~> 0.13.1")`)? 

Can we go with `~> 0.13` instead, having in mind that httparty is 0.16.x already?

That's a blocker for me to use another gem.

**Comment by xxswingxx** [comment]
Hi, mmmm there should be no real reason behind that. I've just uploaded a 1.15.2 with a more relaxed requirement. Close this issue if you feel if the update fixes this for you or add a PR if you need to modify anything else.

**Comment by ivopashov** [comment]
Thanks, looks good now.
