### ISSUE TITLE
Create fails

### ISSUE THREAD

**Issue by vishakhasawant** [quaderno/quaderno-ruby#4]
Hi John Wu,
Thanks for such a nice gem. We are using your latest version of gem i.e. 1.6.0 in  our project and found below issue with create.
It seems you forgot '?'  for is_a_document at line no.64 in crud.rb.

NameError: undefined local variable or method `is_a_document' for Quaderno::Contact:Class
 from /usr/local/rvm/gems/ruby-2.2.0/gems/quaderno-1.6.0/lib/quaderno-ruby/behavior/crud.rb:64:in `create'

Right now we switch back to 1.5.5 version as it is working fine.

**Comment by xxswingxx** [comment]
Hi! Big sorry! Version 1.6.0 has been yanked. You should use 1.6.1

**Comment by vishakhasawant** [comment]
Thanks a ton. We will use 1.6.1 now.

**Comment by xxswingxx** [comment]
If this works for you, can you please close this this issue?

**Comment by vishakhasawant** [comment]
I am closing this issue as It is working now.
