### ISSUE TITLE
IndexError: string not matched on Invoice Create

### ISSUE THREAD

**Issue by mvelikov** [quaderno/quaderno-ruby#7]
When I try to create **a big invoice** I get a very strange unhandled exception:
```
response = Quaderno::Invoice.create build
IndexError: string not matched
	from /home/rbank/main-app/vendor/bundle/ruby/2.1.0/gems/quaderno-1.8.0/lib/quaderno-ruby/behavior/crud.rb:19:in `[]='
	from /home/rbank/main-app/vendor/bundle/ruby/2.1.0/gems/quaderno-1.8.0/lib/quaderno-ruby/behavior/crud.rb:19:in `parse'
	from /home/rbank/main-app/vendor/bundle/ruby/2.1.0/gems/quaderno-1.8.0/lib/quaderno-ruby/behavior/crud.rb:64:in `create'
```

The reason for the exception is that `element` on `19:   element['payments'] = payments_collection` is a string and not a hash:

```
response = Quaderno::Invoice.create(rb_invoice)

From: /Users/mihailvelikov/.rvm/gems/ruby-2.1.2/gems/quaderno-1.8.0/lib/quaderno-ruby/behavior/crud.rb @ line 19 Quaderno::Behavior::Crud::ClassMethods#parse:

    14: def parse(element)
    15:   payments_collection = []
    16:   (element['payments'] || []).each do |payment|
    17:     payments_collection << api_model.to_instance(Quaderno::Payment, payment)
    18:   end unless api_model == Quaderno::Estimate
 => 19:   binding.pry
    20:   element['payments'] = payments_collection
    21: 
    22:   items_collection = []
    23:   element['items'].each do |item|
    24:     items_collection << api_model.to_instance(Quaderno::DocumentItem, item)
    25:   end
    26:   element['items'] = items_collection
    27: 
    28:   contact = api_model.to_instance(Quaderno::Contact, element['contact'])
    29:   element['contact'] = contact
    30: end

[2] pry(Quaderno::Invoice)> puts element
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
```

I have just emailed you the invoice I use to get this kind of issue.

**Comment by xxswingxx** [comment]
It's probably caused because your sample data is too big. Quaderno internal calculations plus the database inserts are resulting in a timeout. So instead of an expected JSON string object, the gem is receiving a non parseable error message in HTML.

**Comment by mvelikov** [comment]
Sure, I am not quite sure if email or github works better.

Yes, this was a test. While I agree it is a normal response from the web server I disagree it is a normal response from an API. I would expect a custom exception and not a Ruby exception.
My understanding in this case is that you should handle this response in the API and throw a proper exception that I can handle in my code.

In the case you do not work with 10000+ line items a check can be added in the sending of the request and throw the exception there and not make me wait and your system try to handle this size of a request.

**Comment by mvelikov** [comment]
@xxswingxx reading once again through your reply I got another idea. What if your database in under high load and inserting just 10 line items takes longer than the web request lifetime and I also get the HTML response?

**Comment by xxswingxx** [comment]
@mvelikov, we've just updated our end to respond with a 422 when a user tries to create more than 200 line items at once. This wrapper should raise the `Quaderno::Exceptions::RequiredFieldsEmptyOrInvalid` exception in those cases with the error message "Too many items".

**Comment by xxswingxx** [comment]
Closing this issue as it seems it has been solved.
